Repository jitacm/30-days-Python-Attack-Defense, pull requests merged in 2025-08, with the labels that each got.

#11 added GUI for Attack_game and added healing funtion
  Attack_defence-game/Attack_game.py
  Attack_defence-game/assets/P1_Shot.png
  Attack_defence-game/assets/P2_Shot.png
Labels: 30daysdevchallenge, jitacm, feature, uiux, level-4

#5 Added AI difficulty levels to the game
  Attack_game_difficulty.py
Labels: 30daysdevchallenge, jitacm, feature, level-2

#22 added bot vs player mode option, added healing ability and fix ui
  Attack_defence-game/app.py
  Attack_defence-game/templates/choose_mode.html
  Attack_defence-game/templates/index.html
Labels: bug, 30daysdevchallenge, jitacm, uiux, level-3
